### ISSUE TITLE
Broken link

### ISSUE THREAD

**Issue by jernst** [undertow-io/undertow-docs#7]
In http://undertow.io/undertow-docs/undertow-docs-1.4.0/index.html#security, the link to Servlet Security (http://undertow.io/undertow-docs/servlet/security.html) is broken -- 404.

Is it supposed to refer to http://undertow.io/undertow-docs/undertow-docs-1.4.0/index.html#servlet-security ?

**Comment by fl4via** [comment]
@jernst you're right. This is fixed in documentation 2.0
